/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Connection, Theme } from "@webpress/core";
export namespace Components {
    interface WpBlockImageDecorator {
        "global": {
    // json set externally by index.php
    context: Connection.Context;
    theme: Theme.Definition;
  };
    }
}
declare global {
    interface HTMLWpBlockImageDecoratorElement extends Components.WpBlockImageDecorator, HTMLStencilElement {
    }
    var HTMLWpBlockImageDecoratorElement: {
        prototype: HTMLWpBlockImageDecoratorElement;
        new (): HTMLWpBlockImageDecoratorElement;
    };
    interface HTMLElementTagNameMap {
        "wp-block-image-decorator": HTMLWpBlockImageDecoratorElement;
    }
}
declare namespace LocalJSX {
    interface WpBlockImageDecorator {
        "global"?: {
    // json set externally by index.php
    context: Connection.Context;
    theme: Theme.Definition;
  };
    }
    interface IntrinsicElements {
        "wp-block-image-decorator": WpBlockImageDecorator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wp-block-image-decorator": LocalJSX.WpBlockImageDecorator & JSXBase.HTMLAttributes<HTMLWpBlockImageDecoratorElement>;
        }
    }
}
