/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Connection } from "@webpress/core";
export namespace Components {
    interface WpBlocksDecorator {
        "global": Connection.Context;
    }
}
declare global {
    interface HTMLWpBlocksDecoratorElement extends Components.WpBlocksDecorator, HTMLStencilElement {
    }
    var HTMLWpBlocksDecoratorElement: {
        prototype: HTMLWpBlocksDecoratorElement;
        new (): HTMLWpBlocksDecoratorElement;
    };
    interface HTMLElementTagNameMap {
        "wp-blocks-decorator": HTMLWpBlocksDecoratorElement;
    }
}
declare namespace LocalJSX {
    interface WpBlocksDecorator {
        "global"?: Connection.Context;
    }
    interface IntrinsicElements {
        "wp-blocks-decorator": WpBlocksDecorator;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wp-blocks-decorator": LocalJSX.WpBlocksDecorator & JSXBase.HTMLAttributes<HTMLWpBlocksDecoratorElement>;
        }
    }
}
