/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Post,
} from '@webpress/core';

export namespace Components {
  interface WpMenu {
    'menu': any;
  }
  interface WpRunningCopy {
    'post': Post;
  }
  interface WpTitle {
    'post': Post;
  }
}

declare global {


  interface HTMLWpMenuElement extends Components.WpMenu, HTMLStencilElement {}
  var HTMLWpMenuElement: {
    prototype: HTMLWpMenuElement;
    new (): HTMLWpMenuElement;
  };

  interface HTMLWpRunningCopyElement extends Components.WpRunningCopy, HTMLStencilElement {}
  var HTMLWpRunningCopyElement: {
    prototype: HTMLWpRunningCopyElement;
    new (): HTMLWpRunningCopyElement;
  };

  interface HTMLWpTitleElement extends Components.WpTitle, HTMLStencilElement {}
  var HTMLWpTitleElement: {
    prototype: HTMLWpTitleElement;
    new (): HTMLWpTitleElement;
  };
  interface HTMLElementTagNameMap {
    'wp-menu': HTMLWpMenuElement;
    'wp-running-copy': HTMLWpRunningCopyElement;
    'wp-title': HTMLWpTitleElement;
  }
}

declare namespace LocalJSX {
  interface WpMenu {
    'menu'?: any;
  }
  interface WpRunningCopy {
    'post'?: Post;
  }
  interface WpTitle {
    'post'?: Post;
  }

  interface IntrinsicElements {
    'wp-menu': WpMenu;
    'wp-running-copy': WpRunningCopy;
    'wp-title': WpTitle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wp-menu': LocalJSX.WpMenu & JSXBase.HTMLAttributes<HTMLWpMenuElement>;
      'wp-running-copy': LocalJSX.WpRunningCopy & JSXBase.HTMLAttributes<HTMLWpRunningCopyElement>;
      'wp-title': LocalJSX.WpTitle & JSXBase.HTMLAttributes<HTMLWpTitleElement>;
    }
  }
}


