/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Post,
} from '@webpress/core';

export namespace Components {
  interface WpTitle {
    'post': Post;
  }
}

declare global {


  interface HTMLWpTitleElement extends Components.WpTitle, HTMLStencilElement {}
  var HTMLWpTitleElement: {
    prototype: HTMLWpTitleElement;
    new (): HTMLWpTitleElement;
  };
  interface HTMLElementTagNameMap {
    'wp-title': HTMLWpTitleElement;
  }
}

declare namespace LocalJSX {
  interface WpTitle {
    'post'?: Post;
  }

  interface IntrinsicElements {
    'wp-title': WpTitle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wp-title': LocalJSX.WpTitle & JSXBase.HTMLAttributes<HTMLWpTitleElement>;
    }
  }
}


