version: "3"

services:
  nginx:
    build:
      context: docker/nginx
    container_name: webpress-nginx
    links:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - webpress-wp:/var/www/html 
      - ./bin/wp-content:/var/www/html/wp-content/
      - ./${WP_UPLOADS_DIR}:/var/www/html/wp-content/uploads
    environment: 
      DOMAIN: ${DOMAIN_NAME}

  mariadb:
    container_name: webpress-mysql
    image: mariadb
    volumes:
      - ./server/sql/install/:/docker-entrypoint-initdb.d
      - ./server/sql/my.cnf:/etc/mysql/conf.d/my.cnf
      - webpress-mysql:/var/lib/mysql:rw
    restart: always
    expose:
      - 3306
    environment: 
      MYSQL_USER: ${MYSQL_WORDPRESS_USER}
      MYSQL_PASSWORD: ${MYSQL_WORDPRESS_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_WORDPRESS_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  wordpress:
    container_name: webpress-wordpress
    depends_on:
      - mariadb
    image: wordpress:latest
    expose:
      - 80
    restart: always
    volumes: 
      - webpress-wp:/var/www/html
      - ./server/wp-content/themes:/var/www/html/wp-content/themes/
      - ./server/app:/var/www/html/app
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_WORDPRESS_HOST}
      WORDPRESS_DB_USER: ${MYSQL_WORDPRESS_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_WORDPRESS_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_WORDPRESS_DATABASE}
      WORDPRESS_CONFIG_EXTRA: | 
        /* Domain */
        define("WP_HOME","https://${DOMAIN_NAME}/");
        define("WP_SITEURL","https://${DOMAIN_NAME}/");
        define('WP_CACHE',true);
        define('WP_MEMORY_LIMIT','128M');
        $$memcached_servers = array(
          'default' => array(
            'memcached:11211',
          )
        );

volumes: 
  webpress-mysql:
  webpress-wp:

networks:
  default:
    external:
      name: webpress-network
    