/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Query,
  ThemeDefinition,
} from '@webpress/core';

export namespace Components {
  interface Wp404 {}
  interface WpHome {}
  interface WpPage {
    'query': Query;
  }
  interface WpPost {
    'query': Query;
  }
  interface WpRoot {
    'theme': ThemeDefinition;
  }
}

declare global {


  interface HTMLWp404Element extends Components.Wp404, HTMLStencilElement {}
  var HTMLWp404Element: {
    prototype: HTMLWp404Element;
    new (): HTMLWp404Element;
  };

  interface HTMLWpHomeElement extends Components.WpHome, HTMLStencilElement {}
  var HTMLWpHomeElement: {
    prototype: HTMLWpHomeElement;
    new (): HTMLWpHomeElement;
  };

  interface HTMLWpPageElement extends Components.WpPage, HTMLStencilElement {}
  var HTMLWpPageElement: {
    prototype: HTMLWpPageElement;
    new (): HTMLWpPageElement;
  };

  interface HTMLWpPostElement extends Components.WpPost, HTMLStencilElement {}
  var HTMLWpPostElement: {
    prototype: HTMLWpPostElement;
    new (): HTMLWpPostElement;
  };

  interface HTMLWpRootElement extends Components.WpRoot, HTMLStencilElement {}
  var HTMLWpRootElement: {
    prototype: HTMLWpRootElement;
    new (): HTMLWpRootElement;
  };
  interface HTMLElementTagNameMap {
    'wp-404': HTMLWp404Element;
    'wp-home': HTMLWpHomeElement;
    'wp-page': HTMLWpPageElement;
    'wp-post': HTMLWpPostElement;
    'wp-root': HTMLWpRootElement;
  }
}

declare namespace LocalJSX {
  interface Wp404 {}
  interface WpHome {}
  interface WpPage {
    'query'?: Query;
  }
  interface WpPost {
    'query'?: Query;
  }
  interface WpRoot {
    'theme'?: ThemeDefinition;
  }

  interface IntrinsicElements {
    'wp-404': Wp404;
    'wp-home': WpHome;
    'wp-page': WpPage;
    'wp-post': WpPost;
    'wp-root': WpRoot;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wp-404': LocalJSX.Wp404 & JSXBase.HTMLAttributes<HTMLWp404Element>;
      'wp-home': LocalJSX.WpHome & JSXBase.HTMLAttributes<HTMLWpHomeElement>;
      'wp-page': LocalJSX.WpPage & JSXBase.HTMLAttributes<HTMLWpPageElement>;
      'wp-post': LocalJSX.WpPost & JSXBase.HTMLAttributes<HTMLWpPostElement>;
      'wp-root': LocalJSX.WpRoot & JSXBase.HTMLAttributes<HTMLWpRootElement>;
    }
  }
}


