/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Query, Template } from "@webpress/core";
import { Hierarchy } from "./model/Hierarchy";
export namespace Components {
    interface WpRouter {
        "query": Query<Template>;
    }
    interface WpRouterTwo {
        "hiearchy": Hierarchy.TemplateHierarchy;
        "query": Query<Template>;
    }
    interface WpTemplate {
        "component": string;
        "definition": Template.Properties;
        "query": Query<Template>;
    }
}
declare global {
    interface HTMLWpRouterElement extends Components.WpRouter, HTMLStencilElement {
    }
    var HTMLWpRouterElement: {
        prototype: HTMLWpRouterElement;
        new (): HTMLWpRouterElement;
    };
    interface HTMLWpRouterTwoElement extends Components.WpRouterTwo, HTMLStencilElement {
    }
    var HTMLWpRouterTwoElement: {
        prototype: HTMLWpRouterTwoElement;
        new (): HTMLWpRouterTwoElement;
    };
    interface HTMLWpTemplateElement extends Components.WpTemplate, HTMLStencilElement {
    }
    var HTMLWpTemplateElement: {
        prototype: HTMLWpTemplateElement;
        new (): HTMLWpTemplateElement;
    };
    interface HTMLElementTagNameMap {
        "wp-router": HTMLWpRouterElement;
        "wp-router-two": HTMLWpRouterTwoElement;
        "wp-template": HTMLWpTemplateElement;
    }
}
declare namespace LocalJSX {
    interface WpRouter {
        "query"?: Query<Template>;
    }
    interface WpRouterTwo {
        "hiearchy"?: Hierarchy.TemplateHierarchy;
        "query"?: Query<Template>;
    }
    interface WpTemplate {
        "component"?: string;
        "definition"?: Template.Properties;
        "query"?: Query<Template>;
    }
    interface IntrinsicElements {
        "wp-router": WpRouter;
        "wp-router-two": WpRouterTwo;
        "wp-template": WpTemplate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wp-router": LocalJSX.WpRouter & JSXBase.HTMLAttributes<HTMLWpRouterElement>;
            "wp-router-two": LocalJSX.WpRouterTwo & JSXBase.HTMLAttributes<HTMLWpRouterTwoElement>;
            "wp-template": LocalJSX.WpTemplate & JSXBase.HTMLAttributes<HTMLWpTemplateElement>;
        }
    }
}
