/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Menu,
  Post,
  TemplateQuery,
  WebpressObject,
} from '@webpress/core';
import {
  WebpressMenuOptions,
} from './components/wp-menu/wp-menu';

export namespace Components {
  interface WpLink {
    'object': WebpressObject;
    'path': string;
  }
  interface WpMenu {
    'menu': Menu;
    'options': WebpressMenuOptions;
    'query': TemplateQuery;
  }
  interface WpRunningCopy {
    'content': string;
    'post': Post;
  }
  interface WpTitle {
    'permalink': boolean;
    'post': Post;
  }
}

declare global {


  interface HTMLWpLinkElement extends Components.WpLink, HTMLStencilElement {}
  var HTMLWpLinkElement: {
    prototype: HTMLWpLinkElement;
    new (): HTMLWpLinkElement;
  };

  interface HTMLWpMenuElement extends Components.WpMenu, HTMLStencilElement {}
  var HTMLWpMenuElement: {
    prototype: HTMLWpMenuElement;
    new (): HTMLWpMenuElement;
  };

  interface HTMLWpRunningCopyElement extends Components.WpRunningCopy, HTMLStencilElement {}
  var HTMLWpRunningCopyElement: {
    prototype: HTMLWpRunningCopyElement;
    new (): HTMLWpRunningCopyElement;
  };

  interface HTMLWpTitleElement extends Components.WpTitle, HTMLStencilElement {}
  var HTMLWpTitleElement: {
    prototype: HTMLWpTitleElement;
    new (): HTMLWpTitleElement;
  };
  interface HTMLElementTagNameMap {
    'wp-link': HTMLWpLinkElement;
    'wp-menu': HTMLWpMenuElement;
    'wp-running-copy': HTMLWpRunningCopyElement;
    'wp-title': HTMLWpTitleElement;
  }
}

declare namespace LocalJSX {
  interface WpLink {
    'object'?: WebpressObject;
    'onWebpressNavigation'?: (event: CustomEvent<{ url }>) => void;
    'path'?: string;
  }
  interface WpMenu {
    'menu'?: Menu;
    'options'?: WebpressMenuOptions;
    'query'?: TemplateQuery;
  }
  interface WpRunningCopy {
    'content'?: string;
    'post'?: Post;
  }
  interface WpTitle {
    'permalink'?: boolean;
    'post'?: Post;
  }

  interface IntrinsicElements {
    'wp-link': WpLink;
    'wp-menu': WpMenu;
    'wp-running-copy': WpRunningCopy;
    'wp-title': WpTitle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'wp-link': LocalJSX.WpLink & JSXBase.HTMLAttributes<HTMLWpLinkElement>;
      'wp-menu': LocalJSX.WpMenu & JSXBase.HTMLAttributes<HTMLWpMenuElement>;
      'wp-running-copy': LocalJSX.WpRunningCopy & JSXBase.HTMLAttributes<HTMLWpRunningCopyElement>;
      'wp-title': LocalJSX.WpTitle & JSXBase.HTMLAttributes<HTMLWpTitleElement>;
    }
  }
}


