/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Post, Template } from "@webpress/core";
export namespace Components {
    interface StarterIndex {
        "query": Template.Query<Post>;
    }
    interface StarterLayout {
    }
    interface StarterSidebar {
        "query": Template.Query;
    }
}
declare global {
    interface HTMLStarterIndexElement extends Components.StarterIndex, HTMLStencilElement {
    }
    var HTMLStarterIndexElement: {
        prototype: HTMLStarterIndexElement;
        new (): HTMLStarterIndexElement;
    };
    interface HTMLStarterLayoutElement extends Components.StarterLayout, HTMLStencilElement {
    }
    var HTMLStarterLayoutElement: {
        prototype: HTMLStarterLayoutElement;
        new (): HTMLStarterLayoutElement;
    };
    interface HTMLStarterSidebarElement extends Components.StarterSidebar, HTMLStencilElement {
    }
    var HTMLStarterSidebarElement: {
        prototype: HTMLStarterSidebarElement;
        new (): HTMLStarterSidebarElement;
    };
    interface HTMLElementTagNameMap {
        "starter-index": HTMLStarterIndexElement;
        "starter-layout": HTMLStarterLayoutElement;
        "starter-sidebar": HTMLStarterSidebarElement;
    }
}
declare namespace LocalJSX {
    interface StarterIndex {
        "query"?: Template.Query<Post>;
    }
    interface StarterLayout {
    }
    interface StarterSidebar {
        "query"?: Template.Query;
    }
    interface IntrinsicElements {
        "starter-index": StarterIndex;
        "starter-layout": StarterLayout;
        "starter-sidebar": StarterSidebar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "starter-index": LocalJSX.StarterIndex & JSXBase.HTMLAttributes<HTMLStarterIndexElement>;
            "starter-layout": LocalJSX.StarterLayout & JSXBase.HTMLAttributes<HTMLStarterLayoutElement>;
            "starter-sidebar": LocalJSX.StarterSidebar & JSXBase.HTMLAttributes<HTMLStarterSidebarElement>;
        }
    }
}
