/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebpressDebug {
    }
}
declare global {
    interface HTMLWebpressDebugElement extends Components.WebpressDebug, HTMLStencilElement {
    }
    var HTMLWebpressDebugElement: {
        prototype: HTMLWebpressDebugElement;
        new (): HTMLWebpressDebugElement;
    };
    interface HTMLElementTagNameMap {
        "webpress-debug": HTMLWebpressDebugElement;
    }
}
declare namespace LocalJSX {
    interface WebpressDebug {
    }
    interface IntrinsicElements {
        "webpress-debug": WebpressDebug;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "webpress-debug": LocalJSX.WebpressDebug & JSXBase.HTMLAttributes<HTMLWebpressDebugElement>;
        }
    }
}
