/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Connection } from "./model/Index";
export namespace Components {
    interface WebpressDebug {
    }
    interface WpGutenbergMedia {
        "global": Connection.Context;
    }
}
declare global {
    interface HTMLWebpressDebugElement extends Components.WebpressDebug, HTMLStencilElement {
    }
    var HTMLWebpressDebugElement: {
        prototype: HTMLWebpressDebugElement;
        new (): HTMLWebpressDebugElement;
    };
    interface HTMLWpGutenbergMediaElement extends Components.WpGutenbergMedia, HTMLStencilElement {
    }
    var HTMLWpGutenbergMediaElement: {
        prototype: HTMLWpGutenbergMediaElement;
        new (): HTMLWpGutenbergMediaElement;
    };
    interface HTMLElementTagNameMap {
        "webpress-debug": HTMLWebpressDebugElement;
        "wp-gutenberg-media": HTMLWpGutenbergMediaElement;
    }
}
declare namespace LocalJSX {
    interface WebpressDebug {
    }
    interface WpGutenbergMedia {
        "global"?: Connection.Context;
    }
    interface IntrinsicElements {
        "webpress-debug": WebpressDebug;
        "wp-gutenberg-media": WpGutenbergMedia;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "webpress-debug": LocalJSX.WebpressDebug & JSXBase.HTMLAttributes<HTMLWebpressDebugElement>;
            "wp-gutenberg-media": LocalJSX.WpGutenbergMedia & JSXBase.HTMLAttributes<HTMLWpGutenbergMediaElement>;
        }
    }
}
