/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  WebpressContext,
} from './theme';

export namespace Components {
  interface WebpressTheme {
    'context': WebpressContext;
  }
}

declare global {


  interface HTMLWebpressThemeElement extends Components.WebpressTheme, HTMLStencilElement {}
  var HTMLWebpressThemeElement: {
    prototype: HTMLWebpressThemeElement;
    new (): HTMLWebpressThemeElement;
  };
  interface HTMLElementTagNameMap {
    'webpress-theme': HTMLWebpressThemeElement;
  }
}

declare namespace LocalJSX {
  interface WebpressTheme {
    'context'?: WebpressContext;
  }

  interface IntrinsicElements {
    'webpress-theme': WebpressTheme;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'webpress-theme': LocalJSX.WebpressTheme & JSXBase.HTMLAttributes<HTMLWebpressThemeElement>;
    }
  }
}


