/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Menu, Post, Query, TemplateQuery, Theme, WebpressObject } from "@webpress/core";
import { WebpressContext } from "./packages/core/src/theme";
import { WebpressMenuOptions } from "./packages/tags/src/components/wp-menu/wp-menu";
export namespace Components {
    interface BhaaDonate {
        "post": Post;
    }
    interface BhaaExpandingCopy {
        "linkText": string;
        "post": Post;
    }
    interface BhaaHeader {
        "query": TemplateQuery;
        "theme": Theme;
    }
    interface BhaaHeartHerald {
        "theme": Theme;
    }
    interface BhaaUpdates {
        "query": Query;
    }
    interface BhaaWrapper {
    }
    interface WebpressTheme {
        "context": WebpressContext;
    }
    interface Wp404 {
    }
    interface WpFrontPage {
        "query": Query;
    }
    interface WpHome {
        "query": Query;
    }
    interface WpLink {
        "object": WebpressObject;
        "path": string;
    }
    interface WpMenu {
        "menu": Menu;
        "options": WebpressMenuOptions;
        "query": TemplateQuery;
    }
    interface WpPage {
        "query": Query;
    }
    interface WpPost {
        "query": Query;
    }
    interface WpRoot {
        "query": TemplateQuery;
        "theme": Theme;
    }
    interface WpRouter {
        "query": TemplateQuery;
    }
    interface WpRunningCopy {
        "content": string;
        "post": Post;
    }
    interface WpTemplate {
        "component": string;
        "componentProps"?: { [key: string]: any };
        "menus": any[];
        "query": Query;
        "sidebars": any[];
    }
    interface WpTitle {
        "permalink": boolean;
        "post": Post;
    }
}
declare global {
    interface HTMLBhaaDonateElement extends Components.BhaaDonate, HTMLStencilElement {
    }
    var HTMLBhaaDonateElement: {
        prototype: HTMLBhaaDonateElement;
        new (): HTMLBhaaDonateElement;
    };
    interface HTMLBhaaExpandingCopyElement extends Components.BhaaExpandingCopy, HTMLStencilElement {
    }
    var HTMLBhaaExpandingCopyElement: {
        prototype: HTMLBhaaExpandingCopyElement;
        new (): HTMLBhaaExpandingCopyElement;
    };
    interface HTMLBhaaHeaderElement extends Components.BhaaHeader, HTMLStencilElement {
    }
    var HTMLBhaaHeaderElement: {
        prototype: HTMLBhaaHeaderElement;
        new (): HTMLBhaaHeaderElement;
    };
    interface HTMLBhaaHeartHeraldElement extends Components.BhaaHeartHerald, HTMLStencilElement {
    }
    var HTMLBhaaHeartHeraldElement: {
        prototype: HTMLBhaaHeartHeraldElement;
        new (): HTMLBhaaHeartHeraldElement;
    };
    interface HTMLBhaaUpdatesElement extends Components.BhaaUpdates, HTMLStencilElement {
    }
    var HTMLBhaaUpdatesElement: {
        prototype: HTMLBhaaUpdatesElement;
        new (): HTMLBhaaUpdatesElement;
    };
    interface HTMLBhaaWrapperElement extends Components.BhaaWrapper, HTMLStencilElement {
    }
    var HTMLBhaaWrapperElement: {
        prototype: HTMLBhaaWrapperElement;
        new (): HTMLBhaaWrapperElement;
    };
    interface HTMLWebpressThemeElement extends Components.WebpressTheme, HTMLStencilElement {
    }
    var HTMLWebpressThemeElement: {
        prototype: HTMLWebpressThemeElement;
        new (): HTMLWebpressThemeElement;
    };
    interface HTMLWp404Element extends Components.Wp404, HTMLStencilElement {
    }
    var HTMLWp404Element: {
        prototype: HTMLWp404Element;
        new (): HTMLWp404Element;
    };
    interface HTMLWpFrontPageElement extends Components.WpFrontPage, HTMLStencilElement {
    }
    var HTMLWpFrontPageElement: {
        prototype: HTMLWpFrontPageElement;
        new (): HTMLWpFrontPageElement;
    };
    interface HTMLWpHomeElement extends Components.WpHome, HTMLStencilElement {
    }
    var HTMLWpHomeElement: {
        prototype: HTMLWpHomeElement;
        new (): HTMLWpHomeElement;
    };
    interface HTMLWpLinkElement extends Components.WpLink, HTMLStencilElement {
    }
    var HTMLWpLinkElement: {
        prototype: HTMLWpLinkElement;
        new (): HTMLWpLinkElement;
    };
    interface HTMLWpMenuElement extends Components.WpMenu, HTMLStencilElement {
    }
    var HTMLWpMenuElement: {
        prototype: HTMLWpMenuElement;
        new (): HTMLWpMenuElement;
    };
    interface HTMLWpPageElement extends Components.WpPage, HTMLStencilElement {
    }
    var HTMLWpPageElement: {
        prototype: HTMLWpPageElement;
        new (): HTMLWpPageElement;
    };
    interface HTMLWpPostElement extends Components.WpPost, HTMLStencilElement {
    }
    var HTMLWpPostElement: {
        prototype: HTMLWpPostElement;
        new (): HTMLWpPostElement;
    };
    interface HTMLWpRootElement extends Components.WpRoot, HTMLStencilElement {
    }
    var HTMLWpRootElement: {
        prototype: HTMLWpRootElement;
        new (): HTMLWpRootElement;
    };
    interface HTMLWpRouterElement extends Components.WpRouter, HTMLStencilElement {
    }
    var HTMLWpRouterElement: {
        prototype: HTMLWpRouterElement;
        new (): HTMLWpRouterElement;
    };
    interface HTMLWpRunningCopyElement extends Components.WpRunningCopy, HTMLStencilElement {
    }
    var HTMLWpRunningCopyElement: {
        prototype: HTMLWpRunningCopyElement;
        new (): HTMLWpRunningCopyElement;
    };
    interface HTMLWpTemplateElement extends Components.WpTemplate, HTMLStencilElement {
    }
    var HTMLWpTemplateElement: {
        prototype: HTMLWpTemplateElement;
        new (): HTMLWpTemplateElement;
    };
    interface HTMLWpTitleElement extends Components.WpTitle, HTMLStencilElement {
    }
    var HTMLWpTitleElement: {
        prototype: HTMLWpTitleElement;
        new (): HTMLWpTitleElement;
    };
    interface HTMLElementTagNameMap {
        "bhaa-donate": HTMLBhaaDonateElement;
        "bhaa-expanding-copy": HTMLBhaaExpandingCopyElement;
        "bhaa-header": HTMLBhaaHeaderElement;
        "bhaa-heart-herald": HTMLBhaaHeartHeraldElement;
        "bhaa-updates": HTMLBhaaUpdatesElement;
        "bhaa-wrapper": HTMLBhaaWrapperElement;
        "webpress-theme": HTMLWebpressThemeElement;
        "wp-404": HTMLWp404Element;
        "wp-front-page": HTMLWpFrontPageElement;
        "wp-home": HTMLWpHomeElement;
        "wp-link": HTMLWpLinkElement;
        "wp-menu": HTMLWpMenuElement;
        "wp-page": HTMLWpPageElement;
        "wp-post": HTMLWpPostElement;
        "wp-root": HTMLWpRootElement;
        "wp-router": HTMLWpRouterElement;
        "wp-running-copy": HTMLWpRunningCopyElement;
        "wp-template": HTMLWpTemplateElement;
        "wp-title": HTMLWpTitleElement;
    }
}
declare namespace LocalJSX {
    interface BhaaDonate {
        "post"?: Post;
    }
    interface BhaaExpandingCopy {
        "linkText"?: string;
        "post"?: Post;
    }
    interface BhaaHeader {
        "query"?: TemplateQuery;
        "theme"?: Theme;
    }
    interface BhaaHeartHerald {
        "theme"?: Theme;
    }
    interface BhaaUpdates {
        "query"?: Query;
    }
    interface BhaaWrapper {
        "onBreakpointChanged"?: (event: CustomEvent<number>) => void;
    }
    interface WebpressTheme {
        "context"?: WebpressContext;
    }
    interface Wp404 {
    }
    interface WpFrontPage {
        "query"?: Query;
    }
    interface WpHome {
        "query"?: Query;
    }
    interface WpLink {
        "object"?: WebpressObject;
        "onWebpressNavigation"?: (event: CustomEvent<{ url }>) => void;
        "path"?: string;
    }
    interface WpMenu {
        "menu"?: Menu;
        "options"?: WebpressMenuOptions;
        "query"?: TemplateQuery;
    }
    interface WpPage {
        "query"?: Query;
    }
    interface WpPost {
        "query"?: Query;
    }
    interface WpRoot {
        "query"?: TemplateQuery;
        "theme"?: Theme;
    }
    interface WpRouter {
        "query"?: TemplateQuery;
    }
    interface WpRunningCopy {
        "content"?: string;
        "post"?: Post;
    }
    interface WpTemplate {
        "component"?: string;
        "componentProps"?: { [key: string]: any };
        "menus"?: any[];
        "query"?: Query;
        "sidebars"?: any[];
    }
    interface WpTitle {
        "permalink"?: boolean;
        "post"?: Post;
    }
    interface IntrinsicElements {
        "bhaa-donate": BhaaDonate;
        "bhaa-expanding-copy": BhaaExpandingCopy;
        "bhaa-header": BhaaHeader;
        "bhaa-heart-herald": BhaaHeartHerald;
        "bhaa-updates": BhaaUpdates;
        "bhaa-wrapper": BhaaWrapper;
        "webpress-theme": WebpressTheme;
        "wp-404": Wp404;
        "wp-front-page": WpFrontPage;
        "wp-home": WpHome;
        "wp-link": WpLink;
        "wp-menu": WpMenu;
        "wp-page": WpPage;
        "wp-post": WpPost;
        "wp-root": WpRoot;
        "wp-router": WpRouter;
        "wp-running-copy": WpRunningCopy;
        "wp-template": WpTemplate;
        "wp-title": WpTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bhaa-donate": LocalJSX.BhaaDonate & JSXBase.HTMLAttributes<HTMLBhaaDonateElement>;
            "bhaa-expanding-copy": LocalJSX.BhaaExpandingCopy & JSXBase.HTMLAttributes<HTMLBhaaExpandingCopyElement>;
            "bhaa-header": LocalJSX.BhaaHeader & JSXBase.HTMLAttributes<HTMLBhaaHeaderElement>;
            "bhaa-heart-herald": LocalJSX.BhaaHeartHerald & JSXBase.HTMLAttributes<HTMLBhaaHeartHeraldElement>;
            "bhaa-updates": LocalJSX.BhaaUpdates & JSXBase.HTMLAttributes<HTMLBhaaUpdatesElement>;
            "bhaa-wrapper": LocalJSX.BhaaWrapper & JSXBase.HTMLAttributes<HTMLBhaaWrapperElement>;
            "webpress-theme": LocalJSX.WebpressTheme & JSXBase.HTMLAttributes<HTMLWebpressThemeElement>;
            "wp-404": LocalJSX.Wp404 & JSXBase.HTMLAttributes<HTMLWp404Element>;
            "wp-front-page": LocalJSX.WpFrontPage & JSXBase.HTMLAttributes<HTMLWpFrontPageElement>;
            "wp-home": LocalJSX.WpHome & JSXBase.HTMLAttributes<HTMLWpHomeElement>;
            "wp-link": LocalJSX.WpLink & JSXBase.HTMLAttributes<HTMLWpLinkElement>;
            "wp-menu": LocalJSX.WpMenu & JSXBase.HTMLAttributes<HTMLWpMenuElement>;
            "wp-page": LocalJSX.WpPage & JSXBase.HTMLAttributes<HTMLWpPageElement>;
            "wp-post": LocalJSX.WpPost & JSXBase.HTMLAttributes<HTMLWpPostElement>;
            "wp-root": LocalJSX.WpRoot & JSXBase.HTMLAttributes<HTMLWpRootElement>;
            "wp-router": LocalJSX.WpRouter & JSXBase.HTMLAttributes<HTMLWpRouterElement>;
            "wp-running-copy": LocalJSX.WpRunningCopy & JSXBase.HTMLAttributes<HTMLWpRunningCopyElement>;
            "wp-template": LocalJSX.WpTemplate & JSXBase.HTMLAttributes<HTMLWpTemplateElement>;
            "wp-title": LocalJSX.WpTitle & JSXBase.HTMLAttributes<HTMLWpTitleElement>;
        }
    }
}
